### ISSUE TITLE
export-block is obsolete now

### ISSUE THREAD

**Issue by ghost** [JalapenoGremlin/ox-trac#4]
This doesn't work with org v9 as export-block is obsolete now. Do you have any plans to fix this?
Thanks for developing this.

**Comment by JalapenoGremlin** [comment]
Apologies for the late response. 

I haven't been using trac for a while (my company moved to another wiki system), but I'll see what can be done. I do use org version 9.1.2 currently, so I'll see what I can do later this weekend.
